#![no_std]

//! Handshake bodies for the footprint demos. Each `run_*_facade()` drives
//! `DefaultStream::connect` end-to-end against the seed-0 canned fixtures
//! generated by `tls_fixture/regen.py` — same surface a real caller would
//! use. The `baseline_*` variants `black_box` the fixture rodata without
//! crypto so the `.text` delta isolates the krabitls + AEAD + sig-verify
//! cost.

// `concat_sh_sf!(SH_LEN, SF_LEN)` expands to a const block that
// concatenates `SERVER_HELLO || SERVER_FLIGHT` at compile time. Done as
// a macro because the generic-const form (`fn f<const A, const B>() ->
// [u8; A + B]`) is gated on the `generic_const_exprs` nightly feature.
// Declared at the top of the crate so the fixture modules below can
// resolve it via the unqualified macro name.
#[cfg(feature = "canned-replay")]
macro_rules! concat_sh_sf {
    ($sh_len:expr, $sf_len:expr) => {{
        let mut out = [0u8; $sh_len + $sf_len];
        let mut i = 0;
        while i < $sh_len {
            out[i] = SERVER_HELLO[i];
            i += 1;
        }
        let mut j = 0;
        while j < $sf_len {
            out[$sh_len + j] = SERVER_FLIGHT[j];
            j += 1;
        }
        out
    }};
}

// Each facade is gated to the exact feature combination its canned bytes
// were generated under. The seed-0 ClientHello changes shape under
// `rsa` (extra sig scheme) and `chacha20` (cipher list), so a build that
// enables one of those alongside the wrong fixture would deterministically
// return `Err(())` even though nothing is actually broken — the wire bytes
// just no longer match what the facade now emits.

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
mod fixture_aes_ed25519_facade {
    pub const CLIENT_HELLO: [u8; 149] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 415] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
mod fixture_chacha_ed25519_facade {
    pub const CLIENT_HELLO: [u8; 149] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 415] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
mod fixture_aes_rsa2048_facade {
    pub const CLIENT_HELLO: [u8; 151] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 1068] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

/// Drive the full facade handshake against canned seed-0 fixtures.
///
/// Composes SH + SF into a `CannedTransport`, then calls
/// `DefaultStream::connect()` with `SeededRng::new(0)` and
/// `ClientParams::self_signed("tls-fixture.local")`. On return the captured
/// TX must equal CH || CF byte-for-byte; otherwise the handshake produced
/// different wire bytes than the Python reference and we return `Err(())`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
pub fn run_aes_ed25519_facade() -> Result<(), ()> {
    use fixture_aes_ed25519_facade::*;
    use krabitls::client::canned::{CannedTransport, SeededRng};
    use krabitls::client::{ClientParams, DefaultScratch, DefaultStream, RuntimeSuitePolicy};

    let mut scratch = DefaultScratch::new();
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<512>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, &mut scratch, transport, &mut rng).map_err(|_| ())?;

    // Captured TX must be CH || CF.
    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len {
        return Err(());
    }
    if captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..] {
        return Err(());
    }
    if captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..] {
        return Err(());
    }
    Ok(())
}

/// Baseline stub: same rodata footprint as `run_aes_ed25519_facade`,
/// without driving any crypto. `.text` delta = full facade-driven
/// handshake cost.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_aes_ed25519_facade() -> bool {
    use core::hint::black_box;
    use fixture_aes_ed25519_facade::*;
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// ChaCha20-Poly1305 + Ed25519 facade variant, chacha-only build.
///
/// Drives `DefaultStream::connect` against the seed-0 fixtures generated
/// by `tls_fixture/regen.py` for the chacha cipher. With `cipher-aes`
/// off, `DefaultConfig::SUITES` resolves to `ConfigSuitePolicy::ChaChaOnly`
/// so the Rust client advertises chacha alone and the server echoes it.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
pub fn run_chacha_ed25519_facade() -> Result<(), ()> {
    use fixture_chacha_ed25519_facade::*;
    use krabitls::client::canned::{CannedTransport, SeededRng};
    use krabitls::client::{ClientParams, DefaultScratch, DefaultStream};

    let mut scratch = DefaultScratch::new();
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<512>::new(&SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local");

    let tls = DefaultStream::connect(&params, &mut scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_chacha_ed25519_facade() -> bool {
    use core::hint::black_box;
    use fixture_chacha_ed25519_facade::*;
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM + RSA-2048-PSS facade variant.
///
/// Same wire path as `run_aes_ed25519_facade`, but with an RSA-PKCS#1-v1.5
/// self-signed cert and an RSA-PSS CertificateVerify in the server flight.
/// Exercises the full RSA-2048 verify path through the facade.
#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
pub fn run_aes_rsa2048_facade() -> Result<(), ()> {
    use fixture_aes_rsa2048_facade::*;
    use krabitls::client::canned::{CannedTransport, SeededRng};
    use krabitls::client::{ClientParams, DefaultScratch, DefaultStream, RuntimeSuitePolicy};

    let mut scratch = DefaultScratch::new();
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<512>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, &mut scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
#[inline(never)]
pub fn baseline_aes_rsa2048_facade() -> bool {
    use core::hint::black_box;
    use fixture_aes_rsa2048_facade::*;
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM + Ed25519 facade variant, HKDF via jedisct1's `hmac-sha256`.
///
/// Reuses the AES+Ed25519 fixture (wire bytes are identical regardless of
/// which `HkdfSha256` impl produces them) and swaps the config's `Hkdf`
/// associated type to [`JedisctCrypto`].
#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
pub fn run_aes_ed25519_jedisct_facade() -> Result<(), ()> {
    use fixture_aes_ed25519_facade::*;
    use krabitls::client::canned::{CannedTransport, SeededRng};
    use krabitls::client::{ClientConfig, ClientParams, ConfigSuitePolicy, Scratch, TlsStream};
    use krabitls::{DerCert, JedisctCrypto, RustCrypto};

    // Local ClientConfig: same as DefaultConfig but with Hkdf swapped to
    // JedisctCrypto so the HKDF / SHA-256 path goes through jedisct1.
    pub struct JedisctConfig;
    impl ClientConfig for JedisctConfig {
        type Hkdf = JedisctCrypto;
        type CertParser = DerCert;
        type Ed25519 = RustCrypto;
        type Rsa = RustCrypto;
        const SUITES: ConfigSuitePolicy = ConfigSuitePolicy::AesOnly;
    }

    type JedisctStream<'s, T> = TlsStream<'s, T, JedisctConfig, 16384, 16645, 4096>;
    type JedisctScratch = Scratch<16384, 16645, 4096>;

    let mut scratch = JedisctScratch::new();
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<512>::new(&SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local");

    let tls = JedisctStream::connect(&params, &mut scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_aes_ed25519_jedisct_facade() -> bool {
    // Shares the AES+Ed25519 fixture rodata.
    baseline_aes_ed25519_facade()
}
