#![no_std]

//! Handshake bodies for the footprint demos. Each `run_*_facade()` drives
//! `DefaultStream::connect` end-to-end against the seed-0 canned fixtures
//! generated by `tls_fixture/regen.py` — same surface a real caller would
//! use. The `baseline_*` variants `black_box` the fixture rodata without
//! crypto so the `.text` delta isolates the krabitls + AEAD + sig-verify
//! cost.

// Static placement for `DefaultScratch` (≈37 KiB). Sized for arbitrary
// RSA chains; placing it on the stack would blow a small MCU's SRAM
// alongside the crypto stack frame and corrupt `.bss`, which manifests as
// an infinite loop under QEMU. Borrow via `with_scratch` under a
// critical section so concurrent facade calls can't share an aliased
// reference even if a future caller adds threads.
#[cfg(feature = "canned-replay")]
mod facade_scratch {
    use core::cell::RefCell;
    use critical_section::Mutex;
    use krabitls::client::DefaultScratch;

    static SCRATCH: Mutex<RefCell<DefaultScratch>> =
        Mutex::new(RefCell::new(DefaultScratch::new()));

    pub fn with<R>(f: impl FnOnce(&mut DefaultScratch) -> R) -> R {
        critical_section::with(|cs| {
            let mut s = SCRATCH.borrow(cs).borrow_mut();
            f(&mut s)
        })
    }
}

// `concat_sh_sf!(SH_LEN, SF_LEN)` expands to a const block that
// concatenates `SERVER_HELLO || SERVER_FLIGHT` at compile time. Done as
// a macro because the generic-const form (`fn f<const A, const B>() ->
// [u8; A + B]`) is gated on the `generic_const_exprs` nightly feature.
#[cfg(feature = "canned-replay")]
macro_rules! concat_sh_sf {
    ($sh_len:expr, $sf_len:expr) => {{
        let mut out = [0u8; $sh_len + $sf_len];
        let mut i = 0;
        while i < $sh_len {
            out[i] = SERVER_HELLO[i];
            i += 1;
        }
        let mut j = 0;
        while j < $sf_len {
            out[$sh_len + j] = SERVER_FLIGHT[j];
            j += 1;
        }
        out
    }};
}

// Each facade is gated to the exact feature combination its canned bytes
// were generated under. The seed-0 ClientHello changes shape under
// `rsa` (extra sig scheme) and `chacha20` (cipher list), so a build that
// enables one of those alongside the wrong fixture would deterministically
// return `Err(())` even though nothing is actually broken — the wire bytes
// just no longer match what the facade now emits.

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
))]
mod fixture_aes_ed25519_facade {
    pub const CLIENT_HELLO: [u8; 149] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 415] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
mod fixture_aes_ecdsa_facade {
    pub const CLIENT_HELLO: [u8; 153] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_ecdsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_ecdsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 678] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_ecdsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_ecdsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

// AES-128-GCM + ECDSA-P256 server cert AND ECDSA-P256 client certificate
// (mutual TLS): the server flight carries a CertificateRequest, and the client
// second flight is `Certificate || CertificateVerify (ECDSA sign) || Finished`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
mod fixture_aes_ecdsa_mtls_facade {
    pub const CLIENT_HELLO: [u8; 153] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_ecdsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_ecdsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 756] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_ecdsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 509] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_ecdsa/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] =
        include_bytes!("../../../testdata/packets_mtls_ecdsa/client_leaf.der");
    /// Big-endian P-256 client scalar for `CLIENT_LEAF` — a test vector.
    pub const CLIENT_SCALAR: [u8; 32] =
        krabitls::hex_decode("ec798c9d6ab974fe4b9d5e5e853e5003e2e2bcef642191c11b97b767964abfdd");
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
mod fixture_chacha_ed25519_facade {
    pub const CLIENT_HELLO: [u8; 149] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 606] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

// ChaCha20-Poly1305 + X25519MLKEM768 hybrid KEX + ML-DSA-44 server cert: the
// leanest full post-quantum config (ChaCha is the lightest cipher backend).
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
mod fixture_chacha_mlkem_mldsa_facade {
    pub const CLIENT_HELLO: [u8; 1339] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha_mlkem_mldsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 1183] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha_mlkem_mldsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 6598] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha_mlkem_mldsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chacha_mlkem_mldsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
mod fixture_aes_rsa2048_facade {
    pub const CLIENT_HELLO: [u8; 151] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 1362] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_rsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
))]
mod fixture_mlkem_ed25519_facade {
    pub const CLIENT_HELLO: [u8; 1333] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 1183] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 584] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
))]
mod fixture_mldsa_facade {
    pub const CLIENT_HELLO: [u8; 155] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mldsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mldsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 6620] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mldsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mldsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
mod fixture_mlkem_mldsa_facade {
    pub const CLIENT_HELLO: [u8; 1339] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem_mldsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 1183] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem_mldsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 6598] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem_mldsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mlkem_mldsa/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
}

// Shared by every facade variant. Gated to "a valid fixture combo is active"
// so a contradictory feature pair (which compiles no fixture module, hence no
// run/baseline function) doesn't drag in unused imports.
#[cfg(all(
    feature = "canned-replay",
    any(
        all(
            feature = "cipher-aes",
            not(feature = "chacha20"),
            not(feature = "rsa")
        ),
        all(
            feature = "chacha20",
            not(feature = "cipher-aes"),
            not(feature = "rsa")
        ),
        all(feature = "rsa", feature = "cipher-aes", not(feature = "chacha20")),
    ),
))]
use {
    core::hint::black_box,
    krabitls::client::{ClientParams, DefaultStream},
    krabitls_fixtures::{CannedTransport, SeededRng},
};

// Only the AES-suite variants (Ed25519, RSA, jedisct) override the suite
// policy; the chacha variant takes the default.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20")
))]
use krabitls::client::RuntimeSuitePolicy;

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
use krabitls::client::EcdsaClientAuth;

// Fixture data globs — one captured-suite module each, so these stay per-cfg.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
use fixture_aes_ecdsa_facade::*;
// Module *alias* (not a glob) — the chain fixture's cfg overlaps the plain-ECDSA
// glob above, so importing its items by name would collide; the chain fns
// reference `fx::CONST` instead.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
use fixture_aes_ecdsa_chain as fx;
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
))]
use fixture_aes_ed25519_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
use fixture_aes_rsa2048_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
use fixture_chacha_ed25519_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
use fixture_chacha_mlkem_mldsa_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
))]
use fixture_mldsa_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
))]
use fixture_mlkem_ed25519_facade::*;
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
use fixture_mlkem_mldsa_facade::*;

// Types unique to the jedisct config (a strict subset of the AES+Ed25519
// combo, so `ClientParams`/`CannedTransport`/`SeededRng` come from above).
#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
use krabitls::backends::{DerCert, JedisctCrypto, RustCrypto};
#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
use krabitls::client::{ClientConfig, ConfigSuitePolicy, DefaultVerify, TlsStream};

// Strategy + validity types for `run_aes_ed25519_facade_clocked`. `DerCert`
// and `TlsStream` also arrive via the jedisct block above when that build is
// on, so they carry an extra `not(jedisct)` guard to dodge a double import.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "cert-der",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
use krabitls::client::{Clocked, DefaultConfig, PinOrSelfSigned, SafeStrategy, TimeSource};
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "cert-der",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "jedisct"),
))]
use krabitls::{backends::DerCert, client::TlsStream};

/// Drive the full facade handshake against canned seed-0 fixtures.
///
/// Composes SH + SF into a `CannedTransport`, then calls
/// `DefaultStream::connect()` with `SeededRng::new(0)` and
/// `ClientParams::self_signed("tls-fixture.local")`. On return the captured
/// TX must equal CH || CF byte-for-byte; otherwise the handshake produced
/// different wire bytes than the Python reference and we return `Err(())`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ed25519_facade() -> Result<(), ()> {
    facade_scratch::with(run_aes_ed25519_facade_with_scratch)
}

/// Run the AES/Ed25519 facade with scratch stored in the current stack frame.
///
/// Hardware cycle measurement uses this form because the shared static-scratch
/// adapter protects its borrow by masking interrupts for the entire handshake.
/// A local scratch value needs no guard, allowing the SysTick overflow handler
/// to extend its counter while the operation runs.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ed25519_facade_on_stack() -> Result<(), ()> {
    let mut scratch = krabitls::client::DefaultScratch::new();
    run_aes_ed25519_facade_with_scratch(&mut scratch)
}

// Same gate as its two callers: the AES/Ed25519 fixtures and
// `RuntimeSuitePolicy` it references are only compiled for that suite, so an
// ungated helper breaks the chacha / rsa / PQC footprint rows.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
// `inline(never)`: a real caller boundary so a single `TlsStream` return slot is
// reused instead of the whole workload folding into the harness `main` (a ~5x
// stack multiplier that measures the rig, not the client).
#[inline(never)]
fn run_aes_ed25519_facade_with_scratch(
    scratch: &mut krabitls::client::DefaultScratch,
) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

/// Same facade as `run_aes_ed25519_facade`, but with a `Clocked` strategy so
/// the (always-compiled) cert validity-window check is exercised. `.text`
/// minus the `NoClock` build = the opt-in cost of validity.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "cert-der",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ed25519_facade_clocked() -> Result<(), ()> {
    struct FixedT(u64);
    impl TimeSource for FixedT {
        fn now_unix_secs(&self) -> u64 {
            self.0
        }
    }

    type ClockedVerify = SafeStrategy<PinOrSelfSigned, DerCert, Clocked<FixedT>>;
    type ClockedStream<'s, T> =
        TlsStream<'s, T, DefaultConfig, ClockedVerify, 16384, 16645, 4096, 8>;

    facade_scratch::with(|scratch| {
        let mut rng = SeededRng::new(0);
        let transport = CannedTransport::<512>::new(&SERVER_STREAM);
        // 2026-06-24T12:00:00Z — inside the fixture cert's validity window.
        let strategy =
            SafeStrategy::with_clock(PinOrSelfSigned::self_signed(), Clocked(FixedT(1782302400)));
        let params = ClientParams::with_strategy("tls-fixture.local", strategy)
            .suite_policy(RuntimeSuitePolicy::Default);

        let tls = ClockedStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

        let captured = tls.transport().captured_tx();
        let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
        if captured.len() != expected_len
            || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
            || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
        {
            return Err(());
        }
        Ok(())
    })
}

/// Baseline stub: same rodata footprint as `run_aes_ed25519_facade`,
/// without driving any crypto. `.text` delta = full facade-driven
/// handshake cost.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_aes_ed25519_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// ChaCha20-Poly1305 + Ed25519 facade variant, chacha-only build.
///
/// Drives `DefaultStream::connect` against the seed-0 fixtures generated
/// by `tls_fixture/regen.py` for the chacha cipher. With `cipher-aes`
/// off, `DefaultConfig::SUITES` resolves to `ConfigSuitePolicy::ChaChaOnly`
/// so the Rust client advertises chacha alone and the server echoes it.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_chacha_ed25519_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_chacha_ed25519)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_chacha_ed25519(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local");

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_chacha_ed25519_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// ChaCha20-Poly1305 + X25519MLKEM768 + ML-DSA-44: the leanest full
/// post-quantum handshake (ChaCha cipher + PQC KEX + PQC cert).
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
pub fn run_chacha_mlkem_mldsa_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_chacha_mlkem_mldsa)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
#[inline(never)]
fn connect_check_chacha_mlkem_mldsa(
    scratch: &mut krabitls::client::DefaultScratch,
) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local");

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_chacha_mlkem_mldsa_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM + RSA-2048-PSS facade variant.
///
/// Same wire path as `run_aes_ed25519_facade`, but with an RSA-PKCS#1-v1.5
/// self-signed cert and an RSA-PSS CertificateVerify in the server flight.
/// Exercises the full RSA-2048 verify path through the facade.
#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
pub fn run_aes_rsa2048_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_aes_rsa2048)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
#[inline(never)]
fn connect_check_aes_rsa2048(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "rsa",
    feature = "cipher-aes",
    not(feature = "chacha20"),
))]
#[inline(never)]
pub fn baseline_aes_rsa2048_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM + Ed25519 facade variant, HKDF via jedisct1's `hmac-sha256`.
///
/// Reuses the AES+Ed25519 fixture (wire bytes are identical regardless of
/// which `HkdfSha256` impl produces them) and swaps the config's `Hkdf`
/// associated type to [`JedisctCrypto`].
#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
pub fn run_aes_ed25519_jedisct_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_aes_ed25519_jedisct)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
fn connect_check_aes_ed25519_jedisct(
    scratch: &mut krabitls::client::DefaultScratch,
) -> Result<(), ()> {
    pub struct JedisctConfig;
    impl ClientConfig for JedisctConfig {
        type Hkdf = JedisctCrypto;
        type CertParser = DerCert;
        type Verifiers = RustCrypto;
        const SUITES: ConfigSuitePolicy = ConfigSuitePolicy::AesOnly;
    }

    type JedisctStream<'s, T> =
        TlsStream<'s, T, JedisctConfig, DefaultVerify, 16384, 16645, 4096, 8>;

    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local");

    let tls = JedisctStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "jedisct",
    feature = "cipher-aes",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_aes_ed25519_jedisct_facade() -> bool {
    baseline_aes_ed25519_facade()
}

/// AES-128-GCM + Ed25519 facade variant with the X25519MLKEM768 hybrid KEX.
///
/// Same facade path as `run_aes_ed25519_facade`, but the seed-0 fixtures were
/// captured advertising the post-quantum hybrid key_share, so `connect()`
/// links the ML-KEM-768 encapsulation path.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
))]
pub fn run_mlkem_ed25519_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_mlkem_ed25519)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_mlkem_ed25519(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_mlkem_ed25519_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM + ML-DSA-44 server-cert facade variant.
///
/// Same facade path as `run_aes_ed25519_facade`, but the server flight carries
/// a self-signed P-256 certificate + ECDSA-P256 CertificateVerify, so
/// `connect()` links the ECDSA verify path.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ecdsa_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_aes_ecdsa)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_aes_ecdsa(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

// AES-128-GCM + ECDSA-P256 with a DEEP intermediate chain validated by the
// `PinnedRoots` chain validator: the server sends leaf + 8 intermediates
// (root omitted), and the client verifies each link up to a stored anchor cert.
// Measures the chain walk's stack — depth is loop-bounded, so this should track
// the shallow ECDSA row, not scale with chain length.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
mod fixture_aes_ecdsa_chain {
    pub const CLIENT_HELLO: [u8; 146] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chain/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chain/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 3909] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chain/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const CLIENT_FINISHED: [u8; 58] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_chain/004_c2s_ClientFinished_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    /// The chain root — stored on the device, NOT transmitted by the server.
    pub const ROOT: &[u8] = include_bytes!("../../../testdata/certs_chain/ca0.der");
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ecdsa_chain_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_aes_ecdsa_chain)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_aes_ecdsa_chain(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<{ fx::CLIENT_HELLO.len() + fx::CLIENT_FINISHED.len() }>::new(
        &fx::SERVER_STREAM,
    );
    let anchors = [krabitls::backends::Anchor::Cert(fx::ROOT)];
    let verify: krabitls::backends::PinnedRoots<
        krabitls::backends::DerCert,
        krabitls::client::NoClock,
        10,
    > = krabitls::backends::PinnedRoots::new(&anchors);
    let params = ClientParams::with_strategy("chain.test", verify);

    // MAX_CHAIN = 10 to admit the 9-cert transmitted chain (leaf + 8 intermediates).
    let tls = krabitls::client::TlsStream::<
        _,
        krabitls::client::DefaultConfig,
        _,
        16384,
        16645,
        4096,
        10,
    >::connect(&params, scratch, transport, &mut rng)
    .map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    if captured.len() != fx::CLIENT_HELLO.len() + fx::CLIENT_FINISHED.len()
        || captured[..fx::CLIENT_HELLO.len()] != fx::CLIENT_HELLO[..]
        || captured[fx::CLIENT_HELLO.len()..] != fx::CLIENT_FINISHED[..]
        || tls.transport().rx_remaining() != 0
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_aes_ecdsa_chain() -> bool {
    black_box(&fx::CLIENT_HELLO);
    black_box(&fx::SERVER_HELLO);
    black_box(&fx::SERVER_FLIGHT);
    black_box(&fx::CLIENT_FINISHED);
    black_box(&fx::ROOT);
    true
}

/// Same AES-128-GCM + ECDSA-P256 path as `run_aes_ecdsa_facade`, but the server
/// flight carries a CertificateRequest and the client answers with its own
/// P-256 certificate + ECDSA CertificateVerify — so `connect()` additionally
/// links the client-auth signing path. This is the stack-cost measurement for
/// an ECDSA client-authenticated handshake.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_aes_ecdsa_mtls_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_aes_ecdsa_mtls)
}

// `inline(never)`: models a real application caller. Behind a call boundary,
// NRVO reuses a single `TlsStream` return slot; inlined into the harness's
// `main` the whole workload folds into one frame where each `Result`/
// `ControlFlow` representation on the return path lands in its own copy — a ~5×
// stack multiplier that measures the harness, not the client. A ~768 B canned
// transport (vs a real ~tens-of-byte NAL socket) is the only remaining rig
// overhead. Fully-qualified `fixture_aes_ecdsa_mtls_facade::*` because the
// module glob is the server-ECDSA fixture and they share const names.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_aes_ecdsa_mtls(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_aes_ecdsa_mtls_facade::CLIENT_HELLO;
    let client_flight = &fixture_aes_ecdsa_mtls_facade::CLIENT_SECOND_FLIGHT;

    let signer = EcdsaClientAuth::p256_from_scalar(
        &fixture_aes_ecdsa_mtls_facade::CLIENT_SCALAR,
        fixture_aes_ecdsa_mtls_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<768>::new(&fixture_aes_ecdsa_mtls_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local")
        .suite_policy(RuntimeSuitePolicy::Default)
        .with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

/// Same facade path as `run_aes_ed25519_facade`, but the server flight carries
/// an ML-DSA-44 certificate + CertificateVerify, so `connect()` links the
/// ML-DSA verify path.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
))]
pub fn run_mldsa_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_mldsa)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
fn connect_check_mldsa(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_aes_ecdsa_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_aes_ecdsa_mtls_facade() -> bool {
    black_box(&fixture_aes_ecdsa_mtls_facade::CLIENT_HELLO);
    black_box(&fixture_aes_ecdsa_mtls_facade::SERVER_HELLO);
    black_box(&fixture_aes_ecdsa_mtls_facade::SERVER_FLIGHT);
    black_box(&fixture_aes_ecdsa_mtls_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_aes_ecdsa_mtls_facade::CLIENT_LEAF);
    black_box(&fixture_aes_ecdsa_mtls_facade::CLIENT_SCALAR);
    true
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
pub fn baseline_mldsa_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// AES-128-GCM facade variant with X25519MLKEM768 KEX and an ML-DSA-44 cert.
///
/// Combines the hybrid PQ key_share of `run_mlkem_ed25519_facade` with the
/// ML-DSA-44 server cert of `run_mldsa_facade`; `connect()` links both PQC
/// paths.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
pub fn run_mlkem_mldsa_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_mlkem_mldsa)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
fn connect_check_mlkem_mldsa(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let mut rng = SeededRng::new(0);
    let transport =
        CannedTransport::<{ CLIENT_HELLO.len() + CLIENT_FINISHED.len() }>::new(&SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = CLIENT_HELLO.len() + CLIENT_FINISHED.len();
    if captured.len() != expected_len
        || captured[..CLIENT_HELLO.len()] != CLIENT_HELLO[..]
        || captured[CLIENT_HELLO.len()..] != CLIENT_FINISHED[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "mlkem",
    feature = "mldsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
))]
#[inline(never)]
pub fn baseline_mlkem_mldsa_facade() -> bool {
    black_box(&CLIENT_HELLO);
    black_box(&SERVER_HELLO);
    black_box(&SERVER_FLIGHT);
    black_box(&CLIENT_FINISHED);
    true
}

/// Links every server-cert verify width into one binary — a `.text` size probe
/// for the full monomorphization set. A single no-auth `connect()` statically
/// references the runtime
/// cert-verify dispatch, so with rsa+ecdsa+mldsa enabled every verify
/// monomorphization is linked — Ed25519 (CAP 16), RSA U1024 (CAP 32) + U2048
/// (CAP 64), ECDSA P-256 (CAP 8) + P-384 (CAP 12), ML-DSA. The empty transport
/// makes `connect` return `Err`; only the *linked* `.text` matters for the size
/// measurement, never run under QEMU.
#[cfg(all(
    feature = "full-stack",
    feature = "canned-replay",
    feature = "cipher-aes"
))]
pub fn run_full_stack() -> bool {
    facade_scratch::with(|scratch| {
        let mut rng = krabitls_fixtures::SeededRng::new(0);
        let transport = krabitls_fixtures::CannedTransport::<2048>::new(&[]);
        let params = krabitls::client::ClientParams::self_signed("x")
            .suite_policy(krabitls::client::RuntimeSuitePolicy::Default);
        // Empty transport → connect returns Err; the probe only needs the
        // symbols linked, so discard the result instead of reporting a failure.
        let _ = krabitls::client::DefaultStream::connect(&params, scratch, transport, &mut rng);
        true
    })
}

// secp256r1 (P-256) ECDHE + AES-128-GCM + ECDSA-P256 server cert — a fully
// coherent all-P-256 handshake (P-256 KEX *and* an ECDSA-P256 leaf). The seed-0
// capture offered X25519 + P-256 and the server selected P-256, so this needs
// `p256-kx` layered on the always-present `x25519-kx`. Server-auth only; there
// is no captured client second flight, so the check pins the ClientHello prefix
// (which proves the P-256 `key_share` was emitted) and that a Finished follows.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
mod fixture_p256_ecdsa_facade {
    pub const CLIENT_HELLO: [u8; 224] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_p256_ecdsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 128] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_p256_ecdsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 653] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_p256_ecdsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    /// The Finished record framing is key-exchange-independent (5-byte record
    /// header + 4-byte handshake header + 32-byte SHA-256 verify_data + 1 inner
    /// content type + 16-byte GCM tag = 58), so the P-256 client Finished is the
    /// same 58 bytes as every other AES row — used to size the TX capture buffer
    /// and assert the exact captured length.
    pub const CLIENT_FINISHED_LEN: usize = 58;
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
pub fn run_p256_ecdsa_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_p256_ecdsa)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
fn connect_check_p256_ecdsa(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_p256_ecdsa_facade::CLIENT_HELLO;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_p256_ecdsa_facade::CLIENT_HELLO.len()
                + fixture_p256_ecdsa_facade::CLIENT_FINISHED_LEN
        },
    >::new(&fixture_p256_ecdsa_facade::SERVER_STREAM);
    let params =
        ClientParams::self_signed("tls-fixture.local").suite_policy(RuntimeSuitePolicy::Default);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + fixture_p256_ecdsa_facade::CLIENT_FINISHED_LEN;
    if captured.len() != expected_len || captured[..client_hello.len()] != client_hello[..] {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mlkem"),
    not(feature = "mldsa"),
))]
#[inline(never)]
pub fn baseline_p256_ecdsa_facade() -> bool {
    black_box(&fixture_p256_ecdsa_facade::CLIENT_HELLO);
    black_box(&fixture_p256_ecdsa_facade::SERVER_HELLO);
    black_box(&fixture_p256_ecdsa_facade::SERVER_FLIGHT);
    true
}

// AES-128-GCM + Ed25519 server cert AND Ed25519 CLIENT certificate (mutual TLS):
// the server flight carries a CertificateRequest and the client second flight is
// `Certificate || CertificateVerify (Ed25519 sign) || Finished`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
mod fixture_ed25519_mtls_facade {
    pub const CLIENT_HELLO: [u8; 150] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 715] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 479] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] = include_bytes!("../../../testdata/packets_mtls/client_leaf.der");
    /// Ed25519 seed for `CLIENT_LEAF` — a test vector, derives its public key.
    pub const CLIENT_SEED: [u8; 32] = [
        0xf2, 0x7f, 0x8c, 0xfc, 0xe9, 0x94, 0x5f, 0x91, 0x13, 0xab, 0xbb, 0xd4, 0x1a, 0x35, 0x94,
        0x91, 0xe6, 0x95, 0xaf, 0x92, 0x35, 0x65, 0xf8, 0xda, 0xc6, 0x25, 0xd1, 0xdd, 0x98, 0x80,
        0x1b, 0xc9,
    ];
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
use krabitls::client::Ed25519ClientAuth;

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
pub fn run_ed25519_mtls_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_ed25519_mtls)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
#[inline(never)]
fn connect_check_ed25519_mtls(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_ed25519_mtls_facade::CLIENT_HELLO;
    let client_flight = &fixture_ed25519_mtls_facade::CLIENT_SECOND_FLIGHT;

    let signer = Ed25519ClientAuth::from_seed(
        &fixture_ed25519_mtls_facade::CLIENT_SEED,
        fixture_ed25519_mtls_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_ed25519_mtls_facade::CLIENT_HELLO.len()
                + fixture_ed25519_mtls_facade::CLIENT_SECOND_FLIGHT.len()
        },
    >::new(&fixture_ed25519_mtls_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("mtls-fixture.local")
        .suite_policy(RuntimeSuitePolicy::Default)
        .with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
#[inline(never)]
pub fn baseline_ed25519_mtls_facade() -> bool {
    black_box(&fixture_ed25519_mtls_facade::CLIENT_HELLO);
    black_box(&fixture_ed25519_mtls_facade::SERVER_HELLO);
    black_box(&fixture_ed25519_mtls_facade::SERVER_FLIGHT);
    black_box(&fixture_ed25519_mtls_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_ed25519_mtls_facade::CLIENT_LEAF);
    black_box(&fixture_ed25519_mtls_facade::CLIENT_SEED);
    true
}

// secp256r1 (P-256) ECDHE + AES-128-GCM + ECDSA-P256 server cert AND ECDSA-P256
// CLIENT certificate (mutual TLS) — a fully coherent all-P-256 mTLS handshake.
// The seed-0 capture offered X25519 + P-256 and the server selected P-256, so
// this needs `p256-kx` layered on the always-present `x25519-kx`; the client
// second flight is `Certificate || CertificateVerify (ECDSA sign) || Finished`.
// Reuses the ECDSA client leaf + scalar from the X25519 `packets_mtls_ecdsa`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "mlkem"),
))]
mod fixture_p256_mtls_facade {
    pub const CLIENT_HELLO: [u8; 224] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_p256_ecdsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 128] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_p256_ecdsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 767] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_p256_ecdsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 509] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_p256_ecdsa/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] =
        include_bytes!("../../../testdata/packets_mtls_p256_ecdsa/client_leaf.der");
    /// Big-endian P-256 client scalar for `CLIENT_LEAF` — a test vector.
    pub const CLIENT_SCALAR: [u8; 32] =
        krabitls::hex_decode("ec798c9d6ab974fe4b9d5e5e853e5003e2e2bcef642191c11b97b767964abfdd");
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "mlkem"),
))]
use krabitls::client::EcdsaClientAuth as EcdsaClientAuthP256;

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "mlkem"),
))]
pub fn run_p256_mtls_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_p256_mtls)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
fn connect_check_p256_mtls(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_p256_mtls_facade::CLIENT_HELLO;
    let client_flight = &fixture_p256_mtls_facade::CLIENT_SECOND_FLIGHT;

    let signer = EcdsaClientAuthP256::p256_from_scalar(
        &fixture_p256_mtls_facade::CLIENT_SCALAR,
        fixture_p256_mtls_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_p256_mtls_facade::CLIENT_HELLO.len()
                + fixture_p256_mtls_facade::CLIENT_SECOND_FLIGHT.len()
        },
    >::new(&fixture_p256_mtls_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("tls-fixture.local")
        .suite_policy(RuntimeSuitePolicy::Default)
        .with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "p256-kx",
    feature = "ecdsa",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
pub fn baseline_p256_mtls_facade() -> bool {
    black_box(&fixture_p256_mtls_facade::CLIENT_HELLO);
    black_box(&fixture_p256_mtls_facade::SERVER_HELLO);
    black_box(&fixture_p256_mtls_facade::SERVER_FLIGHT);
    black_box(&fixture_p256_mtls_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_p256_mtls_facade::CLIENT_LEAF);
    black_box(&fixture_p256_mtls_facade::CLIENT_SCALAR);
    true
}

// AES-128-GCM + Ed25519 server cert + RSA-2048-PSS CLIENT certificate (mutual
// TLS): the server flight carries a CertificateRequest and the client answers
// with `Certificate || CertificateVerify (RSA-PSS sign) || Finished`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
mod fixture_rsa_mtls_facade {
    pub const CLIENT_HELLO: [u8; 152] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 709] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 926] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] =
        include_bytes!("../../../testdata/packets_mtls_rsa/client_leaf.der");
    /// Throwaway RSA-2048 client key — a test vector certified by `CLIENT_LEAF`.
    pub const CLIENT_N: [u8; 256] = krabitls::hex_decode(
        "a2906830b167480a497efc6bbbe503a038fe4778e6e04f09f2e2e3667140beb6\
         397a86523c0e9129820665dd7d69e60ceac0d9988addfcb9a3316de6f4084af8\
         4f70250a833f057bfa960ec8ede6889c4ca3b79c0decfc394b02e8581ba46dfe\
         132e734223e34900368d9bb2a5087a2c595a444c4b232fc95cc2a766a9e10f7b\
         c4842c28275a0f131ea0ea3d5ffefa208f52a723be2e85beed036195bf96ea5a\
         fa5e28716d708ef59b281d1b80c782e1b18b4992602085f478d550588520d994\
         37ebd17189824cf61f5c0389051167a0679c17e87c61bb1f9a8765bb3a4d0251\
         f1cf04f81ed426c1bd3c9618ac5f8574fe89ce6b89b4945dd58c1a39ac911ba5",
    );
    pub const CLIENT_D: [u8; 256] = krabitls::hex_decode(
        "14f43731db941c019372a657beaae8da3cae6e0903fd72c2ae0797d72b0ef4e6\
         2927856bd128f1861fa7f27667c5802d370f2f9d0d7d4aa7a504e88d25f471b1\
         6b0fe1fe666777ae00e159bb858abb1e2674cde474191173d31ae757000d244e\
         652b8e18bee67b90e6f73ed3fa98caa2afcbc654ed347662e6ad828565ad4860\
         ef65d75740448190eb2d75aaec68fde78e20eeca81d98505b084d3859c49fc3b\
         2130beb6b8b2076321d28ba4b35bc3213336a109579990a2eb1fbede6632a5d9\
         1a2ef0459fa077e28691a503f9ca369966de82923328b58a1ea295f47b85cca8\
         f2b36cd39a0a93234d2da7313c9191a307c80bd271f0ff74be8a4665149eb791",
    );
    pub const CLIENT_E: u32 = 65537;
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
use krabitls::client::RsaClientAuth;

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
pub fn run_rsa_mtls_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_rsa_mtls)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
fn connect_check_rsa_mtls(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_rsa_mtls_facade::CLIENT_HELLO;
    let client_flight = &fixture_rsa_mtls_facade::CLIENT_SECOND_FLIGHT;

    let signer = RsaClientAuth::from_components(
        &fixture_rsa_mtls_facade::CLIENT_N,
        fixture_rsa_mtls_facade::CLIENT_E,
        &fixture_rsa_mtls_facade::CLIENT_D,
        fixture_rsa_mtls_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_rsa_mtls_facade::CLIENT_HELLO.len()
                + fixture_rsa_mtls_facade::CLIENT_SECOND_FLIGHT.len()
        },
    >::new(&fixture_rsa_mtls_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("mtls-fixture.local")
        .suite_policy(RuntimeSuitePolicy::Default)
        .with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
pub fn baseline_rsa_mtls_facade() -> bool {
    black_box(&fixture_rsa_mtls_facade::CLIENT_HELLO);
    black_box(&fixture_rsa_mtls_facade::SERVER_HELLO);
    black_box(&fixture_rsa_mtls_facade::SERVER_FLIGHT);
    black_box(&fixture_rsa_mtls_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_rsa_mtls_facade::CLIENT_LEAF);
    black_box(&fixture_rsa_mtls_facade::CLIENT_N);
    black_box(&fixture_rsa_mtls_facade::CLIENT_D);
    true
}

// AES-128-GCM + RSA-2048 server cert AND RSA-2048-PSS CLIENT certificate (mutual
// TLS): both server-auth (RSA verify) and client-auth (RSA sign) run RSA-2048, so
// this row isolates the cost of an all-RSA mutual handshake. The server flight
// carries a CertificateRequest and the client answers with
// `Certificate || CertificateVerify (RSA-PSS sign) || Finished`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
mod fixture_rsa_mtls_srv_facade {
    pub const CLIENT_HELLO: [u8; 152] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa_srv/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa_srv/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 1475] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa_srv/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 936] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_rsa_srv/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] =
        include_bytes!("../../../testdata/packets_mtls_rsa_srv/client_leaf.der");
    /// Throwaway RSA-2048 client key — a test vector certified by `CLIENT_LEAF`.
    pub const CLIENT_N: [u8; 256] = krabitls::hex_decode(
        "a2906830b167480a497efc6bbbe503a038fe4778e6e04f09f2e2e3667140beb6\
         397a86523c0e9129820665dd7d69e60ceac0d9988addfcb9a3316de6f4084af8\
         4f70250a833f057bfa960ec8ede6889c4ca3b79c0decfc394b02e8581ba46dfe\
         132e734223e34900368d9bb2a5087a2c595a444c4b232fc95cc2a766a9e10f7b\
         c4842c28275a0f131ea0ea3d5ffefa208f52a723be2e85beed036195bf96ea5a\
         fa5e28716d708ef59b281d1b80c782e1b18b4992602085f478d550588520d994\
         37ebd17189824cf61f5c0389051167a0679c17e87c61bb1f9a8765bb3a4d0251\
         f1cf04f81ed426c1bd3c9618ac5f8574fe89ce6b89b4945dd58c1a39ac911ba5",
    );
    pub const CLIENT_D: [u8; 256] = krabitls::hex_decode(
        "14f43731db941c019372a657beaae8da3cae6e0903fd72c2ae0797d72b0ef4e6\
         2927856bd128f1861fa7f27667c5802d370f2f9d0d7d4aa7a504e88d25f471b1\
         6b0fe1fe666777ae00e159bb858abb1e2674cde474191173d31ae757000d244e\
         652b8e18bee67b90e6f73ed3fa98caa2afcbc654ed347662e6ad828565ad4860\
         ef65d75740448190eb2d75aaec68fde78e20eeca81d98505b084d3859c49fc3b\
         2130beb6b8b2076321d28ba4b35bc3213336a109579990a2eb1fbede6632a5d9\
         1a2ef0459fa077e28691a503f9ca369966de82923328b58a1ea295f47b85cca8\
         f2b36cd39a0a93234d2da7313c9191a307c80bd271f0ff74be8a4665149eb791",
    );
    pub const CLIENT_E: u32 = 65537;
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
pub fn run_rsa_mtls_srv_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_rsa_mtls_srv)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`. Uses the
// `RsaClientAuth` import shared with `connect_check_rsa_mtls`.
#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
fn connect_check_rsa_mtls_srv(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_rsa_mtls_srv_facade::CLIENT_HELLO;
    let client_flight = &fixture_rsa_mtls_srv_facade::CLIENT_SECOND_FLIGHT;

    let signer = RsaClientAuth::from_components(
        &fixture_rsa_mtls_srv_facade::CLIENT_N,
        fixture_rsa_mtls_srv_facade::CLIENT_E,
        &fixture_rsa_mtls_srv_facade::CLIENT_D,
        fixture_rsa_mtls_srv_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_rsa_mtls_srv_facade::CLIENT_HELLO.len()
                + fixture_rsa_mtls_srv_facade::CLIENT_SECOND_FLIGHT.len()
        },
    >::new(&fixture_rsa_mtls_srv_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("mtls-fixture.local")
        .suite_policy(RuntimeSuitePolicy::Default)
        .with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "cipher-aes",
    feature = "rsa",
    feature = "client-auth",
    not(feature = "p256-kx"),
    not(feature = "blinding"),
    not(feature = "chacha20"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
))]
#[inline(never)]
pub fn baseline_rsa_mtls_srv_facade() -> bool {
    black_box(&fixture_rsa_mtls_srv_facade::CLIENT_HELLO);
    black_box(&fixture_rsa_mtls_srv_facade::SERVER_HELLO);
    black_box(&fixture_rsa_mtls_srv_facade::SERVER_FLIGHT);
    black_box(&fixture_rsa_mtls_srv_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_rsa_mtls_srv_facade::CLIENT_LEAF);
    black_box(&fixture_rsa_mtls_srv_facade::CLIENT_N);
    black_box(&fixture_rsa_mtls_srv_facade::CLIENT_D);
    true
}

// ChaCha20-Poly1305 + Ed25519 server cert AND Ed25519 CLIENT certificate (mutual
// TLS), chacha-only build: the server flight carries a CertificateRequest and the
// client second flight is `Certificate || CertificateVerify (Ed25519 sign) ||
// Finished`. Same mutual path as `fixture_ed25519_mtls_facade` but with the AEAD
// swapped to ChaCha20-Poly1305.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
mod fixture_chacha_mtls_facade {
    pub const CLIENT_HELLO: [u8; 150] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_chacha/001_c2s_ClientHello.hex"
    ));
    pub const SERVER_HELLO: [u8; 95] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_chacha/002_s2c_ServerHello.hex"
    ));
    pub const SERVER_FLIGHT: [u8; 718] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_chacha/003_s2c_ServerFlight_encrypted.hex"
    ));
    /// Client `Certificate || CertificateVerify || Finished` (one AEAD record).
    pub const CLIENT_SECOND_FLIGHT: [u8; 497] = krabitls::hex_decode(include_str!(
        "../../../testdata/packets_mtls_chacha/004_c2s_ClientSecondFlight_encrypted.hex"
    ));
    pub const SERVER_STREAM: [u8; SERVER_HELLO.len() + SERVER_FLIGHT.len()] =
        concat_sh_sf!(SERVER_HELLO.len(), SERVER_FLIGHT.len());
    pub const CLIENT_LEAF: &[u8] =
        include_bytes!("../../../testdata/packets_mtls_chacha/client_leaf.der");
    /// Ed25519 seed for `CLIENT_LEAF` — a test vector, derives its public key.
    pub const CLIENT_SEED: [u8; 32] = [
        0xf2, 0x7f, 0x8c, 0xfc, 0xe9, 0x94, 0x5f, 0x91, 0x13, 0xab, 0xbb, 0xd4, 0x1a, 0x35, 0x94,
        0x91, 0xe6, 0x95, 0xaf, 0x92, 0x35, 0x65, 0xf8, 0xda, 0xc6, 0x25, 0xd1, 0xdd, 0x98, 0x80,
        0x1b, 0xc9,
    ];
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
use krabitls::client::Ed25519ClientAuth as ChaChaEd25519ClientAuth;

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
pub fn run_chacha_mtls_facade() -> Result<(), ()> {
    facade_scratch::with(connect_check_chacha_mtls)
}

// `inline(never)`: models a real application caller so the measured stack is the
// client's, not the harness's — see `connect_check_aes_ecdsa_mtls`. No
// `suite_policy` override: with `cipher-aes` off the default policy is ChaChaOnly.
#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
#[inline(never)]
fn connect_check_chacha_mtls(scratch: &mut krabitls::client::DefaultScratch) -> Result<(), ()> {
    let client_hello = &fixture_chacha_mtls_facade::CLIENT_HELLO;
    let client_flight = &fixture_chacha_mtls_facade::CLIENT_SECOND_FLIGHT;

    let signer = ChaChaEd25519ClientAuth::from_seed(
        &fixture_chacha_mtls_facade::CLIENT_SEED,
        fixture_chacha_mtls_facade::CLIENT_LEAF,
    )
    .map_err(|_| ())?;
    let mut rng = SeededRng::new(0);
    let transport = CannedTransport::<
        {
            fixture_chacha_mtls_facade::CLIENT_HELLO.len()
                + fixture_chacha_mtls_facade::CLIENT_SECOND_FLIGHT.len()
        },
    >::new(&fixture_chacha_mtls_facade::SERVER_STREAM);
    let params = ClientParams::self_signed("mtls-fixture.local").with_client_auth(&signer);

    let tls = DefaultStream::connect(&params, scratch, transport, &mut rng).map_err(|_| ())?;

    let captured = tls.transport().captured_tx();
    let expected_len = client_hello.len() + client_flight.len();
    if captured.len() != expected_len
        || captured[..client_hello.len()] != client_hello[..]
        || captured[client_hello.len()..] != client_flight[..]
    {
        return Err(());
    }
    Ok(())
}

#[cfg(all(
    feature = "canned-replay",
    feature = "chacha20",
    feature = "client-auth",
    not(feature = "blinding"),
    not(feature = "cipher-aes"),
    not(feature = "rsa"),
    not(feature = "mldsa"),
    not(feature = "ecdsa"),
    not(feature = "mlkem"),
    not(feature = "p256-kx"),
))]
#[inline(never)]
pub fn baseline_chacha_mtls_facade() -> bool {
    black_box(&fixture_chacha_mtls_facade::CLIENT_HELLO);
    black_box(&fixture_chacha_mtls_facade::SERVER_HELLO);
    black_box(&fixture_chacha_mtls_facade::SERVER_FLIGHT);
    black_box(&fixture_chacha_mtls_facade::CLIENT_SECOND_FLIGHT);
    black_box(fixture_chacha_mtls_facade::CLIENT_LEAF);
    black_box(&fixture_chacha_mtls_facade::CLIENT_SEED);
    true
}
