#![no_main]
#![no_std]

//! Cortex-M footprint example: AES-128-GCM-SHA256 + Ed25519. Drives the
//! full TLS 1.3 facade (`DefaultStream::connect`) against the seed-0
//! canned fixtures generated by `tls_fixture/regen.py`.

use cortex_m_rt::entry;

#[cfg(feature = "jtrace-f407")]
fn run_handshake() -> bool {
    footprint_handshakes::run_aes_ed25519_facade_on_stack().is_ok()
}

#[cfg(not(feature = "jtrace-f407"))]
fn run_handshake() -> bool {
    footprint_handshakes::run_aes_ed25519_facade().is_ok()
}

#[entry]
fn main() -> ! {
    footprint_cortex_m::test_fixture(
        #[cfg(feature = "baseline")]
        || footprint_handshakes::baseline_aes_ed25519_facade(),
        #[cfg(not(feature = "baseline"))]
        run_handshake,
        "krabitls",
    );
    loop {
        cortex_m::asm::nop();
    }
}
