#![no_main]
#![no_std]

//! Cortex-M footprint example: ChaCha20-Poly1305-SHA256 + Ed25519. Drives
//! the full TLS 1.3 facade (`DefaultStream::connect`) against the seed-0
//! canned fixtures generated by `tls_fixture/regen.py` under the chacha
//! cipher. Build with `--no-default-features --features chacha20,cert-der,canned-replay`
//! so AES is genuinely absent from `.text`.

use cortex_m_rt::entry;

#[entry]
fn main() -> ! {
    footprint_cortex_m::test_fixture(
        #[cfg(feature = "baseline")]
        || footprint_handshakes::baseline_chacha_ed25519_facade(),
        #[cfg(not(feature = "baseline"))]
        || footprint_handshakes::run_chacha_ed25519_facade().is_ok(),
        "krabitls_chacha",
    );
    loop {
        cortex_m::asm::nop();
    }
}
